import { Instrument_Sans, Azeret_Mono } from "next/font/google";
import "./globals.css";

const iSans = Instrument_Sans({
  variable: "--font-i-sans",
  subsets: ["latin"],
});

const azeret = Azeret_Mono({
  variable: "--font-azeret",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unusual",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${iSans.variable} ${azeret.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
